# 搜索关键词
keyWords: 
- 信小兔
- 移动硬盘
- 董觅生
- pigwang499
- 3740691119
- xingchi123

# 最低评论数
lowCommentNum: 10
# 最低值率
lowWorthyNum: 50
# 满意商品数量
satisfyNum: 10
# 过滤词
filterWords: 
- "榴莲"
- "唯品会"
- "牛奶"
- "过期"
- "售罄"

# 定时任务多长执行一次 单位秒 默认 3个小时
tickTime: 10800
# 钉钉token
dingdingToken: "106aef404757b5a5c7df598663a9590f7ad67a4edd82ed255faee5dbc986776a"