# 搜索关键词
keyWords: 

# 最低评论数
lowCommentNum: 1
# 最低值率
lowWorthyNum: 10
# 满意商品数量
satisfyNum: 10
# 过滤词
filterWords: 
- "过期"
- "售罄"

# 定时任务多长执行一次 单位秒 默认 3个小时
tickTime: 5
# 钉钉token
dingdingToken: "106aef404757b5a5c7df598663a9590f7ad67a4edd82ed255faee5dbc986776a"

# 签到时间(默认早上8:30)
cron: "0 10 10 ? * *"
