name: ci

on:
  push:
    branches:
      - master

env: # 设置环境变量
  TZ: Asia/Shanghai # 时区（设置时区可使页面中的`最近更新时间`使用时区时间）

jobs: 
  build:
    runs-on: ubuntu-latest # 运行在虚拟机环境ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1 # 作用：检出仓库，获取源码。
      - name: set-go-environment
        uses: actions/setup-go@v3 # uses 和 run 不能同时在一个step使用
        with:
          go-version: '1.13.1'
      - run: go version

