name: ci

on:
  push:
    branches:
      - master

env: # 设置环境变量
  TZ: Asia/Shanghai # 时区（设置时区可使页面中的`最近更新时间`使用时区时间）


jobs: 
  build:
    runs-on: ubuntu-latest # 运行在虚拟机环境ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1 # 作用：检出仓库，获取源码。
      - name: set-go-environment
        uses: actions/setup-go@v3 # uses 和 run 不能同时在一个step使用
        with:
          go-version: '1.13.1'
      - name: build-app
        run: go build -o smzdmPusher
      - name: depoly
        uses: ./.github/actions/cd
        with:
          # 这里是 rsync 的参数 switches: -avzh --delete --exclude="" --include="" --filter=""
          switches: -avzh
          path: ./smzdmPusher ./smzdm.sh
          remote_path: /opt/go/smzdmForGo
          remote_host: 1.15.141.114
          remote_port: 22
          remote_user: root
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
          cmd:  systemctl restart smzdm.service

